-- 권한 등록
INSERT INTO AUTHORITY (AUTHORITY, AUTHORITY_NAME, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('ROLE_ADMIN', '관리자', 'admin@naver.com', 'admin@naver.com', NOW(), NOW());
INSERT INTO AUTHORITY (AUTHORITY, AUTHORITY_NAME, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('ROLE_USER', '회원', 'admin@naver.com', 'admin@naver.com', NOW(), NOW());

-- 회원 등록(비번 1234)
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('관리자', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'admin@naver.com', '01011112222', 'ACTIVITY', 'admin@naver.com', 'admin@naver.com', NOW(), NOW());
INSERT INTO MEMBER (NAME, PASSWORD, EMAIL, HP, STATUS, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('회원', '$2a$10$is4cfHcYBgNPhcTMW2e8c.gd0EdqYShhhicWddNX28zfQUQkDJrq2', 'member@naver.com', '01011112222', 'ACTIVITY', 'member@naver.com', 'member@naver.com', NOW(), NOW());

-- 회원 권한 등록
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO MEMBER_AUTHORITY (MEMBER_ID, AUTHORITY_ID) VALUES (2, 2);

-- 게시판 등록
INSERT INTO BOARD_MANAGER (NAME, DESCRIPTION, BOARD_TYPE, BOARD_USE_YN, COMMENT_USE_YN, CREATE_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('공지사항', '공지사항게시판', 'NOTICE', 'Y', 'Y', 'admin@naver.com', 'admin@naver.com', NOW(), NOW());